version: '3.7'

# Make sure you disable userland networking, for proper perf tests.

services:
  zk-service:
    image: bitnami/zookeeper:3.5.5
    hostname: zk-service
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      JVMFLAGS: -javaagent:/tmp/fullgc-agent.jar -server -Xms25m -Xmx512m -XX:+UseG1GC -Djava.awt.headless=true -XX:MaxMetaspaceExpansion=2M -XX:+TieredCompilation -XX:+HeapDumpOnOutOfMemoryError -XX:GCHeapFreeLimit=5 -XX:GCTimeLimit=90 -noverify -XX:ReservedCodeCacheSize=256m -Djava.security.egd=file:/dev/./urandom -Dcom.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.fastBoot=true -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -Dcom.sun.xml.internal.bind.v2.bytecode.ClassTailor.noOptimize=true -XX:SoftRefLRUPolicyMSPerMB=5 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses
    volumes:
#      - ./zookeeper/zk-log4j.properties:/conf/log4j.properties
      - ./java/fullgc-agent.jar:/tmp/fullgc-agent.jar
  kafka-zk:
    image: bitnami/zookeeper:3.4.14
    hostname: kafka-zk
    ports:
      - "2183:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      JVMFLAGS: -javaagent:/tmp/fullgc-agent.jar -server -Xms25m -Xmx512m -XX:+UseG1GC -Djava.awt.headless=true -XX:MaxMetaspaceExpansion=2M -XX:+TieredCompilation -XX:+HeapDumpOnOutOfMemoryError -XX:GCHeapFreeLimit=5 -XX:GCTimeLimit=90 -noverify -XX:ReservedCodeCacheSize=256m -Djava.security.egd=file:/dev/./urandom -Dcom.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.fastBoot=true -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -Dcom.sun.xml.internal.bind.v2.bytecode.ClassTailor.noOptimize=true -XX:SoftRefLRUPolicyMSPerMB=5 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses
    volumes:
#      - ./zookeeper/zk-log4j.properties:/conf/log4j.properties
      - ./java/fullgc-agent.jar:/tmp/fullgc-agent.jar
  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    depends_on:
      - kafka-zk
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: kafka-zk:2181
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_MESSAGE_MAX_BYTES: 10000012
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT_MS: 10000
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "true"
      KAFKA_LEADER_IMBALANCE_CHECK_INTERVAL_SECONDS: 5
      LOG4J_LOGGER_ORG: WARN,STDOUT
      LOG4J_LOGGER_ORG_APACHE_KAFKA: WARN,STDOUT
      LOG4J_LOGGER_KAFKA: WARN,STDOUT
      KAFKA_JVM_PERFORMANCE_OPTS: -javaagent:/tmp/fullgc-agent.jar -server -Xms25m -Xmx512m -XX:+UseG1GC -Djava.awt.headless=true -XX:MaxMetaspaceExpansion=2M -XX:+TieredCompilation -XX:+HeapDumpOnOutOfMemoryError -XX:GCHeapFreeLimit=5 -XX:GCTimeLimit=90 -noverify -XX:ReservedCodeCacheSize=256m -Djava.security.egd=file:/dev/./urandom -Dcom.sun.xml.internal.bind.v2.runtime.JAXBContextImpl.fastBoot=true -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -Dcom.sun.xml.internal.bind.v2.bytecode.ClassTailor.noOptimize=true -XX:SoftRefLRUPolicyMSPerMB=5 -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses
      KAFKA_CREATE_TOPICS: "payout.succeeded:4:1,twTasks.demoapp.executeTask.default:4:1,twTasks.demoapp.executeTask.email:4:1"
    volumes:
      - ./java/fullgc-agent.jar:/tmp/fullgc-agent.jar
#  mysql:
#    image: mysql:8
#    hostname: mysql
#    ports:
#      - "13306:3306"
#    environment:
#      MYSQL_DATABASE: demoapp
#      MYSQL_ROOT_PASSWORD: example-password-change-me
#    command: mysqld --max_connections=200 --ssl=0 --innodb_buffer_pool_size=256m --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --transaction-isolation=READ-COMMITTED
  mariadb:
    image: mariadb:10.3
    hostname: mysql
    ports:
      - "13307:3306"
    environment:
      MYSQL_DATABASE: demoapp
      MYSQL_ROOT_PASSWORD: example-password-change-me
    command: "mysqld --innodb_flush_log_at_trx_commit=1 --innodb_flush_method=O_DIRECT_NO_FSYNC --max_connections=200 --ssl=0
    --innodb_buffer_pool_size=2g
    --character-set-server=utf8mb4
    --collation-server=utf8mb4_unicode_ci --transaction-isolation=READ-COMMITTED"
  postgres:
    image: postgres:10
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: example-password-change-me
    volumes:
      - ./postgres//postgre-initdb.d:/docker-entrypoint-initdb.d
    command: -c 'max_connections=200'

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 14.8.0.0/24
